name: Build Project
on: [push, pull_request]

jobs:
  build:
    # Only run on PRs if the source branch is on someone else's repo
    if: ${{ github.event_name != 'pull_request' || github.repository != github.event.pull_request.head.repo.full_name }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [8, 11, 17]
      fail-fast: true
    steps:
      - uses: actions/checkout@v2
      - name: JDK ${{ matrix.java }}
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'
          cache: 'gradle'
      - name: Patch and build
        run: |
          chmod u+x ./gradlew
          ./gradlew build --stacktrace
